baseURL = 'https://sergei.kimmel.works/'
languageCode = 'en-us'
title = 'Sergei Kimmel'
theme = "paper"

[services]
  [services.googleAnalytics]
    ID = 'G-24FL02B8QR'

[params]
  description = 'Sergei Kimmel personal site'
  github = 'al-kimmel-serj'
  linkedin = 'sergei-kimmel'
  rss = true

  avatar = 'al.kimmel.serj@gmail.com'
  name = 'Sergei Kimmel'
  bio = 'Software Engineer'

  monoDarkIcon = true
  math = true
